on: 
  workflow_dispatch:
  push:

jobs:
  rebuild_droplet_job:
    runs-on: ubuntu-latest
    name: Rebuild Digital Ocean Droplet
    steps:
    - name: Trigger droplet rebuild & wait for completion
      uses: chrisjsimpson/droplet-rebuild-action@v0.3
      with:
        digital-ocean-access-token: ${{ secrets.digital-ocean-access-token }}
        droplet-id: ${{ secrets.droplet-id }}
        image: ${{ secrets.image }}
